### ISSUE TITLE
pre-alignment

### ISSUE THREAD

**Issue by KnudNorNielsen** [bcgsc/tigmint#105]
Within the section 'tips' it is stated: "If your barcoded reads are in multiple FASTQ files, the initial alignments of the barcoded reads to the draft assembly can be done in parallel and merged prior to running Tigmint." What should then be the input for 'tigmint-make tigmint-long'? A paf file?

**Comment by lcoombe** [comment]
Hi @KnudNorNielsen,

Good question! We took a slightly different approach for tigmint-long, where we used piping to speed up a few of the steps:
https://github.com/bcgsc/tigmint/blob/master/bin/tigmint-make#L280-L288

So unfortunately the short answer is that there isn't an equivalent for parallelizing the long read alignments for tigmint-long, as the pseudo-linked read simulation, alignment and molecule inference is done together in a single, piped step. Your best bet is to just use a concatenated reads file - the step should be faster than the tigmint (default mode) equivalent, due to the use of minimap, outputting a PAF file, and the fact that no sorting is required. 
If there's interest to update Tigmint (tigmint-long mode) to allow for multiple input long reads files, we could certainly add that to our 'wishlist'.

Thank you for your interest in Tigmint!
Lauren
