### ISSUE TITLE
Forward+reverse + long reads

### ISSUE THREAD

**Issue by aabaricalla** [bcgsc/tigmint#115]
Hi there!
I'm reading the documentation and I have a few doubts.

I have 10X linked reads (forward+reverse) and a Pacbio+ONT longreads files.

What would be the best choice to run first: Tigmint or Tigmint-Long?
If tigmint is the choice, I should pre-align each read in a separate round of BWA and then sort+merge them?

Thanks in advance!

**Comment by lcoombe** [comment]
Hello @aabaricalla,

We haven't done a lot of tests with running sequential Tigmint runs using the different read evidence, but I tend to work with the rule of thumb of using shorter-range evidence first, then longer-range later. So, I'd suggest running Tigmint-long first. Depending on how large your genome is, the other option would be to run your pipeline with both orders of Tigmint, and then see which of them gives you the best result.

For your linked read question - are your linked reads separated into multiple files? 

Thanks for your interest in Tigmint!
Lauren

**Comment by aabaricalla** [comment]
Hi @lcoombe, thanks for the quick response.
I have a forward + a reverse (10x_Genomics_1.fastq.gz + 10x_Genomics_2.fastq.gz).
What's your suggestion in this case? run twice? interleave the files?

**Comment by lcoombe** [comment]
Hi @aabaricalla,
With separate forward/reverse files, the easiest thing to do would be to interleave the forward/reverse files to a single fastq file. Then, you could just use the `tigmint-make` Makefile to run all the Tigmint steps for you. It's best to run the alignments of the forward/reverse reads together with bwa since it can use pairing information in generating the alignments.
