### ISSUE TITLE
Unknown error preventing tigmint-make across multiple installation methods

### ISSUE THREAD

**Issue by DrPintoThe2nd** [bcgsc/tigmint#24]
Hi all,
Thanks for all your work developing this tool, it looks extremely useful!
I'd really love to get this tool up and running on my workstation. However, I receive this error no matter which installation method I try, which genome version, etc...

>./bin/tigmint-make tigmint draft=draft.fasta reads=barcoded.fastq.gz
"make: *** No rule to make target 'draft.fasta.barcoded.fastq.gz.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa', needed by 'tigmint'.  Stop."

Specs: Ubuntu 16.04, Intel Xeon 48 threads, 128 Gb RAM, 8Gb Graphics card.. and a cool mouse?..
Any guidance would be greatly appreciated!
Best,
bjp

**Comment by lcoombe** [comment]
Hi @DrPintoThe2nd ,

I'm guessing that since you closed this, you've figured it out, but I'll post the answer here anyway in case it helps another user.

You just will need to omit the suffixes from the specified ```draft``` and ```reads```. Ie, with this command: 
```
tigmint-make tigmint draft=draft reads=barcoded
```
tigmint expects to see an assembly called draft.fa and reads called barcoded.fq.gz in the current working directory.

**Comment by DrPintoThe2nd** [comment]
HA! Yes that was it!
Of course I couldn't have figured it out a few hours earlier!

Thanks for all your work on this! Really excited for this tool!
Best,
bjp
