### ISSUE TITLE
pip installation corrupt

### ISSUE THREAD

**Issue by schellt** [bcgsc/tigmint#26]
When installing tigmint via `pip3 install tigmint` the shebangs of the python scripts are hard coded (and obviously not working on every system).
```
$ head -1 /usr/bin/tigmint*
==> /usr/bin/tigmint <==
#!/bin/sh

==> /usr/bin/tigmint-arcs-tsv <==
#!/usr/local/opt/python/bin/python3.7

==> /usr/bin/tigmint-cut <==
#!/usr/local/opt/python/bin/python3.7

==> /usr/bin/tigmint-make <==
#!/usr/bin/make -rRf

==> /usr/bin/tigmint-molecule <==
#!/usr/local/opt/python/bin/python3.7
```

**Comment by aakashsur** [comment]
I had the same issue, I ostensibly need to change the shebangs. Not sure where this could be remedied. Running without changing it leads to the following error - `/usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory`

**Comment by lcoombe** [comment]
Hi @aakashsur,

Could you try installing Tigmint using `conda` or `brew`? The `pip` distribution is not up to date, unfortunately.

**Comment by aakashsur** [comment]
Thanks for the heads up, I've gone ahead and installed from source since I'm working on a cluster and already had a python virtual environment with most of the things I need. I'll let you know if I run into any issues, at the very least, the python shebangs are now `/usr/bin/env python3` which appear to circumvent the issue with the pip install.

**Comment by lcoombe** [comment]
Great, I'm glad you found that workaround! I will remove the `pip3 install tigmint` instructions from the README for now, since as I mentioned it still has an older version and as you reported, doesn't work for all systems.
